# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
